Sprint3
ClevertecFrontendLab/Alexandra789 pull request #1
Opened 2023-02-16 18:25 UTC by Alexandra789

2023-02-16 18:40 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676572816/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676572816/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676572816/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676572816/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676572816/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676572816/main-loading.png)

2023-02-16 18:45 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676573132/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676573132/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676573132/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676573132/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676573132/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676573132/main-loading.png)

2023-02-16 18:48 UTC, SergeyGlazun requested changes

2023-02-16 18:48 UTC, SergeyGlazun commented on yarn.lock
>    integrity sha512-F27qZr8uUqwhWZboondsPx8tnC3Ct3SxZA3V5WyEvujRyyNv0VYPhoBg1gZ8/MV5tubQp76Trw8lTv9hzRBa+A==
![image](https://user-images.githubusercontent.com/70904466/219459114-20be7d6f-bef5-4409-b4d2-5cffd01758d3.png)
должно быть сообщение об ошибки  прекратиться загрузка

2023-02-16 18:48 UTC, SergeyGlazun commented on yarn.lock
>    integrity sha512-F27qZr8uUqwhWZboondsPx8tnC3Ct3SxZA3V5WyEvujRyyNv0VYPhoBg1gZ8/MV5tubQp76Trw8lTv9hzRBa+A==
и тут 
![image](https://user-images.githubusercontent.com/70904466/219459466-3e3dee5e-b392-41b1-ae94-866acc0c4d2b.png)

2023-02-16 20:16 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676578595/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676578595/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676578595/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676578595/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676578595/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676578595/main-loading.png)

2023-02-16 20:29 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676579352/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676579352/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676579352/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676579352/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676579352/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676579352/main-loading.png)

2023-02-16 20:32 UTC, SergeyGlazun requested changes

2023-02-16 20:32 UTC, SergeyGlazun commented on .editorconfig
> +root = true
![image](https://user-images.githubusercontent.com/70904466/219480198-a31f3cd0-8be1-430d-97bc-75477765cfa0.png)
при ошибки должна пропасть загрузка и появиться уведомление об ошибке

2023-02-16 20:46 UTC, Alexandra789 commented on .editorconfig
> +root = true
@SergeyGlazun у меня появляется загрузка пока данные подтягиваются, если есть ошибка, то после лоадера появляется уведомление, а тесты успевают только лоадер заскринить
Или нужно чтобы лоадера вообще не было  на этой странице, если ошибка?

2023-02-17 11:23 UTC, Alexandra789 commented on .editorconfig
> +root = true
@SergeyGlazun прикрепляю видео и скрин уведомления об ошибке 
https://www.loom.com/share/c0ea8ba9590d4601816dfe1b613cf189
![image](https://user-images.githubusercontent.com/60068127/219637229-33e354d2-747b-42f6-934b-97a0dd09cfcd.png)

2023-02-17 12:23 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676636587/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676636587/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676636587/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676636587/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676636587/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676636587/main-loading.png)

2023-02-17 12:29 UTC, SergeyGlazun requested changes

2023-02-17 12:29 UTC, SergeyGlazun commented on src/redux/sagas/categories/index.js
>  import {ALL_CATEGORIES_URL} from "../../../constants/url";
![image](https://user-images.githubusercontent.com/70904466/219653824-e127d40f-4a9b-4128-9e2c-448016b03358.png)

2023-02-17 12:29 UTC, SergeyGlazun commented on src/redux/sagas/categories/index.js
>  import {ALL_CATEGORIES_URL} from "../../../constants/url";
строки поиска по макету не должно быть

2023-02-17 14:02 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676642523/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676642523/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676642523/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676642523/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676642523/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Alexandra789/1676642523/main-loading.png)

2023-02-17 14:02 UTC, Alexandra789 commented on src/redux/sagas/categories/index.js
>  import {ALL_CATEGORIES_URL} from "../../../constants/url";
@SergeyGlazun 
![image](https://user-images.githubusercontent.com/60068127/219673673-86a4a437-e340-4be5-b322-12fff11ad787.png)
![image](https://user-images.githubusercontent.com/60068127/219674554-87aab98a-4d72-40ff-9ebd-b0e81c502470.png)

2023-02-17 14:51 UTC, SergeyGlazun approved these changes

2023-02-17 15:01 UTC, merged